package backlog

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// _priority.md holds the stack-rank order of items inside a backlog. Top
// of the file is the next iteration. Items below fall into later
// iterations or the "untimed" tail. _icebox.md holds the same shape but
// for items not yet committed to a window. The two files together must
// reference every active item exactly once. Sync enforces that
// invariant.
const (
	priorityFileName = "_priority.md"
	iceboxFileName   = "_icebox.md"
)

// OrderEntry is one line in a priority or icebox file: `- [title](path)`.
// Path is relative to the backlog directory the file sits in.
type OrderEntry struct {
	Title string
	Path  string
}

// OrderFile is an ordered list of OrderEntry. Index 0 is highest rank.
// Header text is reformatted on every Save().
type OrderFile struct {
	path    string
	header  string
	entries []OrderEntry
}

var orderLineRe = regexp.MustCompile(`^\s*-\s*\[([^\]]+)\]\(([^)]+)\)\s*$`)

// LoadOrderFile reads an order file from disk. Missing file returns an
// empty OrderFile, not an error.
func LoadOrderFile(path, header string) (*OrderFile, error) {
	f := &OrderFile{path: path, header: header}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return f, nil
		}
		return nil, err
	}
	sc := bufio.NewScanner(strings.NewReader(string(data)))
	for sc.Scan() {
		m := orderLineRe.FindStringSubmatch(sc.Text())
		if m != nil {
			f.entries = append(f.entries, OrderEntry{Title: m[1], Path: strings.TrimSpace(m[2])})
		}
	}
	return f, nil
}

func (f *OrderFile) Path() string             { return f.path }
func (f *OrderFile) Entries() []OrderEntry    { return append([]OrderEntry(nil), f.entries...) }
func (f *OrderFile) Len() int                 { return len(f.entries) }
func (f *OrderFile) IsEmpty() bool            { return len(f.entries) == 0 }

// IndexOf returns the index of the entry with the given path, or -1.
func (f *OrderFile) IndexOf(itemFile string) int {
	for i, e := range f.entries {
		if e.Path == itemFile {
			return i
		}
	}
	return -1
}

// Remove drops the entry with the given path. No-op if not present.
func (f *OrderFile) Remove(itemFile string) bool {
	i := f.IndexOf(itemFile)
	if i < 0 {
		return false
	}
	f.entries = append(f.entries[:i], f.entries[i+1:]...)
	return true
}

// InsertTop inserts e at index 0.
func (f *OrderFile) InsertTop(e OrderEntry) { f.InsertAt(0, e) }

// InsertBottom appends e.
func (f *OrderFile) InsertBottom(e OrderEntry) { f.entries = append(f.entries, e) }

// InsertAt inserts e at the given index. Index is clamped to [0, len].
func (f *OrderFile) InsertAt(i int, e OrderEntry) {
	if i < 0 {
		i = 0
	}
	if i > len(f.entries) {
		i = len(f.entries)
	}
	out := make([]OrderEntry, 0, len(f.entries)+1)
	out = append(out, f.entries[:i]...)
	out = append(out, e)
	out = append(out, f.entries[i:]...)
	f.entries = out
}

// MoveTo moves an existing entry to a new index. Returns false if absent.
func (f *OrderFile) MoveTo(itemFile string, newIndex int) bool {
	i := f.IndexOf(itemFile)
	if i < 0 {
		return false
	}
	e := f.entries[i]
	f.entries = append(f.entries[:i], f.entries[i+1:]...)
	f.InsertAt(newIndex, e)
	return true
}

// MoveAfter places `itemFile` immediately after `anchor`. If anchor is
// not present or empty, places at top. Returns false if itemFile is not
// already in the file.
func (f *OrderFile) MoveAfter(itemFile, anchor string) bool {
	if f.IndexOf(itemFile) < 0 {
		return false
	}
	if anchor == "" {
		return f.MoveTo(itemFile, 0)
	}
	ai := f.IndexOf(anchor)
	if ai < 0 {
		return f.MoveTo(itemFile, len(f.entries)-1)
	}
	// Remove first so indices are stable
	f.Remove(itemFile)
	if ai > f.IndexOf(anchor) {
		ai = f.IndexOf(anchor)
	}
	target := f.IndexOf(anchor) + 1
	f.InsertAt(target, OrderEntry{Title: titleFor(itemFile), Path: itemFile})
	return true
}

// MoveBefore places `itemFile` immediately before `anchor`.
func (f *OrderFile) MoveBefore(itemFile, anchor string) bool {
	if f.IndexOf(itemFile) < 0 {
		return false
	}
	if anchor == "" {
		return f.MoveTo(itemFile, 0)
	}
	e, ok := f.entryFor(itemFile)
	if !ok {
		return false
	}
	f.Remove(itemFile)
	ai := f.IndexOf(anchor)
	if ai < 0 {
		f.entries = append(f.entries, e)
		return true
	}
	f.InsertAt(ai, e)
	return true
}

func (f *OrderFile) entryFor(p string) (OrderEntry, bool) {
	for _, e := range f.entries {
		if e.Path == p {
			return e, true
		}
	}
	return OrderEntry{}, false
}

// Save writes the order file back to disk with a fresh header.
func (f *OrderFile) Save() error {
	var b strings.Builder
	if f.header != "" {
		fmt.Fprintf(&b, "# %s\n\nStack-rank order. Top is the highest priority. Edit by hand or via `am rank` / `am ice` / `am unice`. Regenerated by `am sync`.\n\n", f.header)
	}
	for _, e := range f.entries {
		fmt.Fprintf(&b, "- [%s](%s)\n", e.Title, e.Path)
	}
	return os.WriteFile(f.path, []byte(b.String()), 0644)
}

// titleFor is a fallback used when MoveAfter rebuilds an entry without a
// known title. Walks the basename minus extension into a Title-Case
// approximation.
func titleFor(itemPath string) string {
	base := strings.TrimSuffix(filepath.Base(itemPath), filepath.Ext(itemPath))
	base = strings.ReplaceAll(base, "-", " ")
	return base
}

// PriorityFilePath returns the path to a backlog's _priority.md file.
func PriorityFilePath(backlogDir string) string { return filepath.Join(backlogDir, priorityFileName) }

// IceboxFilePath returns the path to a backlog's _icebox.md file.
func IceboxFilePath(backlogDir string) string { return filepath.Join(backlogDir, iceboxFileName) }

// LoadPriority loads a backlog's _priority.md file.
func LoadPriority(backlogDir string) (*OrderFile, error) {
	return LoadOrderFile(PriorityFilePath(backlogDir), "Priority")
}

// LoadIcebox loads a backlog's _icebox.md file.
func LoadIcebox(backlogDir string) (*OrderFile, error) {
	return LoadOrderFile(IceboxFilePath(backlogDir), "Icebox")
}

// EnforceOrderInvariant ensures every active item in the backlog is in
// exactly one of priority/icebox. Items in both are kept in priority and
// removed from icebox. Items in neither are appended to icebox bottom.
// Order entries that no longer match a real item are dropped (orphan
// link cleanup). Returns (priority, icebox, changed).
func EnforceOrderInvariant(bck *Backlog, backlogDir string) (*OrderFile, *OrderFile, bool, error) {
	pri, err := LoadPriority(backlogDir)
	if err != nil {
		return nil, nil, false, err
	}
	ice, err := LoadIcebox(backlogDir)
	if err != nil {
		return nil, nil, false, err
	}
	changed := false

	active := bck.ActiveItems()
	known := make(map[string]*BacklogItem, len(active))
	for _, item := range active {
		rel := filepath.Base(item.Path())
		known[rel] = item
	}

	// Drop priority entries that point at items no longer present.
	for _, e := range append([]OrderEntry(nil), pri.Entries()...) {
		if _, ok := known[e.Path]; !ok {
			pri.Remove(e.Path)
			changed = true
		}
	}
	// Same for icebox.
	for _, e := range append([]OrderEntry(nil), ice.Entries()...) {
		if _, ok := known[e.Path]; !ok {
			ice.Remove(e.Path)
			changed = true
		}
	}

	// Items in both: priority wins.
	for _, e := range pri.Entries() {
		if ice.IndexOf(e.Path) >= 0 {
			ice.Remove(e.Path)
			changed = true
		}
	}

	// Items in neither: append to icebox.
	for _, item := range active {
		rel := filepath.Base(item.Path())
		if pri.IndexOf(rel) < 0 && ice.IndexOf(rel) < 0 {
			ice.InsertBottom(OrderEntry{Title: item.Title(), Path: rel})
			changed = true
		}
	}

	// Refresh stored titles to current truth.
	for i, e := range pri.entries {
		if it, ok := known[e.Path]; ok && it.Title() != "" {
			if pri.entries[i].Title != it.Title() {
				pri.entries[i].Title = it.Title()
				changed = true
			}
		}
	}
	for i, e := range ice.entries {
		if it, ok := known[e.Path]; ok && it.Title() != "" {
			if ice.entries[i].Title != it.Title() {
				ice.entries[i].Title = it.Title()
				changed = true
			}
		}
	}

	return pri, ice, changed, nil
}
